# Generated by Django 2.1.4 on 2018-12-21 18:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0003_auto_20181221_1834'),
    ]

    operations = [
        migrations.CreateModel(
            name='Links',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.URLField(max_length=2100)),
                ('article', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='articles.Article')),
            ],
        ),
        migrations.RemoveField(
            model_name='link',
            name='article',
        ),
        migrations.DeleteModel(
            name='Link',
        ),
    ]
